name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v6
        with:
          distribution: liberica
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Build project
        run: ./gradlew build --no-daemon

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain

      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v6
        with:
          name: spotbugs-report
          path: build/reports/spotbugs/main.html

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
